# Generated by Django 2.0.5 on 2020-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chatt_app', '0002_auto_20200730_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeeting',
            name='meeting_id',
            field=models.BigIntegerField(),
        ),
    ]
