# Generated by Django 2.0.5 on 2020-07-06 07:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_chatt_app', '0005_studentreport_subject_teacher_user_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeeting',
            name='meeting_name',
        ),
        migrations.AddField(
            model_name='usermeeting',
            name='meeting_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermeeting',
            name='meeting_subject',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='video_chatt_app.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermeeting',
            name='meeting_topic',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='video_chatt_app.Topic'),
            preserve_default=False,
        ),
    ]
