# Generated by Django 2.0.5 on 2020-07-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chatt_app', '0006_auto_20200706_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeeting',
            name='meeting_id',
            field=models.IntegerField(),
        ),
    ]
