# Generated by Django 2.0.5 on 2020-07-06 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_chatt_app', '0007_auto_20200706_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_grade', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userrole',
            name='grade_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video_chatt_app.UserGrade'),
            preserve_default=False,
        ),
    ]
