# Generated by Django 2.0.5 on 2020-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chatt_app', '0008_auto_20200706_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='answer_corrent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
