# Generated by Django 2.0.5 on 2020-07-15 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_chatt_app', '0009_auto_20200707_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_chatt_app.UserGrade')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='grade_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='option1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='option2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
