# Generated by Django 2.0.5 on 2020-07-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_chatt_app', '0010_auto_20200715_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeeting',
            name='grade_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video_chatt_app.UserGrade'),
            preserve_default=False,
        ),
    ]
